### ISSUE TITLE
Slow performance on Linux with simultaneous requests

### ISSUE THREAD

**Issue by janigro** [IBM-Swift/SwiftKueryMySQL#57] opened 2019-04-28 16:52 UTC
Hello, I’ve hit a performance issue with Swift-KueryMySQL. These are the conditions under which the problem occurs:

1. Several requests are made simultaneously. 
2. Kitura is running on Linux (Mac works fine).

To illustrate the symptoms, this is what happens with my Kitura application:

When the browser loads the application, it makes 9 simultaneous xhr requests, each retrieving a json object with data obtained from the mysql database. For example, on a Mac, one of the files takes 100 ms to be received (that is normal). On Linux, it takes 5 seconds. That is 50 times slower! If the same request is made alone, it loads fine. The problem appears when multiple requests hit Kitura simultaneously.

Then, I discover that if after loading the page, I quickly hit the refresh button, this time the requests respond normally (as with the Mac). I can repeat it again and again and it always works fine. However, if I wait 3 or 4 seconds before hitting the refresh, then it is slow again.

So I started debugging, focusing mainly on my own code, but I could not find any issues. Then I began looking to the KueryMySQL code, trying to measure the time spent in each function. What I found, is that in all the functions that call DispatchQueue.global().async (there are only 6), sometimes there is a big delay (> 1 second) between the call and the execution of its closure. 5 of the functions are in _**MySQLConnection.swift**_ and 1 is in _**MySQLResultFetcher.swift**_

In order to try to isolate the problem, I replaced all async calls by sync calls, hoping to see the delay shifting somewhere else. The big surprise was that this change “fixed” the problem. All requests now respond immediately. I am attaching a capture of the times with the code running async vs sync.

It is ironic that running asynchronously works much slower than synchronously.

![dispatch](https://user-images.githubusercontent.com/26244860/56867458-abaa4200-69e5-11e9-9471-832690a37e1d.jpg)

I do understand that changing _**DispatchQueue.global().async**_ to _**DispatchQueue.global().sync**_ goes against the changes in SwiftKuery 3.0. However, so far, this is the only way I have found to circumvent my problem.

I don’t know if this is a problem in SwiftKuery, Linux GCD implementation or the mysqlclient library on Linux. However, I have spent too much time in this already and cannot continue to investigate the issue further.

I must disclose something about the way I use the library. I started using SwiftKuery way back, before the changes in 3.0. When you guys made that big async change, I already had a very large project and I could not afford to go back and rewrite everything. So I created a synchronous version of the main functions and moved on with my life. I did this for execute, asRows, etc. Nothing fancy, they just call the original API, but wait for a semaphore to be raised. It is the same pattern followed by connectSync() in the MySQLConnection class. This should not be a problem and in fact it works just fine on the Mac, however, I thought I should mention.

Also important, I am using Kitura-Net, not Kitura-NIO. It is beta and I found it to be extremely buggy with crashes in different places. I did compile it once with NIO, but it did not seem to make much of a difference. However, because it crashed continuously, I cannot offer any conclusive feedback on that.

I have been trying to create a small testing project showing the performance problem, but was unable to replicate it. It seems the issue needs some complexity to manifest itself. I am way behind on my project, but if I can manage to find some time, I will try again.

Finally, wouldn’t it be possible to have either a global setting or a per-connection setting that instructs the library to act synchronously or asynchronously? This would let the user of the library to decide how he/she wants to use it. It would certainly make my life much easier!

Cheers,
Javier.-

**Comment by janigro** [comment] 2019-04-28 18:24
I forgot to mentioned that I also tried changing DispatchQueue.global() with a different queue created exclusively for SwiftKueryMySQL, The intention was to avoid any possible conflict with other libraries that might also use the global queue. However, it made no difference.

**Comment by janigro** [comment] 2019-04-30 08:13
Hi, I finally made some time and created a project that demonstrates the problems. The project is available at: https://github.com/janigro/k-bug.git

Please do read its README.md file. It contains all the information needed to build, run and test it.

**Comment by kilnerm** [comment] 2019-04-30 08:21
@janigro, I will take a look. Thanks for your efforts so far.

**Comment by kilnerm** [comment] 2019-06-24 13:22
@janigro,

I have spent sometime looking into the issue and the behaviour your application is exhibiting can be attributed to a combination of factors.

The Linux implementation of Dispatch scales up the number of available threads in its pool less aggressively than on Apple platforms. This is because it is not coupled to the kernel as tightly and relies on a polling mechanism to determine whether scaling is necessary. This polling occurs once per second and the number of threads will be increased by 1 per poll.

The Dispatch implementation also scales threads down aggressively. After a few seconds of inactivity the number of available threads returns to its initial value.

When this behaviour is coupled with actions that cause threads to block the issue becomes more observable as the available pool of threads is artificially decreased in size due to the blocked threads.

So in the sample application without semaphores the threads calling the database will return to the pool when they offload the call to the database back onto the global dispatch queue asynchronously but the database call will block another thread until it completes. When you add in the additional semaphores wrapping the Kuery API the problem is exasperated as each call will now block two threads.

From testing with both sync and async versions of MySQL I observe that the async version does perform better in terms of overall elapsed time, the time from the first request beginning processing to the last request completing processing. When not using semaphores the timings are almost identical. 

When using semaphores I can see a huge difference between the async and sync versions. This is due to an increase in the number of blocked threads.

Overall in both scenarios the no Sempahore version outperformed its semaphore counterpart.

Submitting requests in quick succession results in better performance because the thread pool grows as required and maintains its size while work is available. When you leave a short interval the pool shrinks which results in timings similar to the initial invocation.

At this stage I would suggest you update the application to not wrap the database calls in a semaphore and use the asynchronous call back model. This should give you a big performance gain which will then be amplified once we have a truly non-blocking database adapter.

**Comment by janigro** [comment] 2019-06-24 15:45
Thank you for taking the time to investigate this. It is good to understand exactly why the framework is behaving the way it is.

For me, updating the entire code, is a titanic task for which I do not have the resources at the moment. For the time being, I keep using semaphores and only updated a few key queries that are common to most requests (session checks, privilege checks, etc.).

I wonder if the new **Combine** framework presented during the WWDC2019 could be used to approach the issue differently. I do not think it is available for Linux yet. I'll be monitoring it.

Thanks again for the detailed explanation.

**Comment by kilnerm** [comment] 2019-07-03 09:01
Marking this as closed

**Closed by kilnerm** 2019-07-03 09:01 UTC
